tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"

cask "font-hack-nerd-font"
cask "iterm2"
brew "pipx"
brew "pyenv"
brew "pyenv-virtualenv"
cask "1password"
cask "google-chrome"
cask "obsidian"
cask "qgis"
cask "visual-studio-code"
cask "docker"
brew "thefuck"