tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/core"

cask "font-hack-nerd-font"
brew "pipx"
brew "pyenv"
brew "pyenv-virtualenv"
cask "google-chrome"
cask "qgis"
cask "visual-studio-code"
cask "docker"
brew "thefuck"